### 어떤 영화가 좋은 평점을 받았는지 분석

In [1]:
import numpy as np

### 1.데이터 불러오기

In [2]:
# genfromtxt
# np.genfromtxt('파일경로', delimiter = '구분자', dtype=자료형)

movie = np.genfromtxt('data/ratings.dat',delimiter='::',dtype=np.int64)

movie

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [3]:
# 데이터를 저장
# savetxt

np.savetxt('data/temp.txt',movie, delimiter=':',fmt='%d') # %d는 정수 자료형을 의미한다.

In [4]:
movie

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

#### 각 열
- 0번 인덱스 열 : 사용자의 id (아이디를 기준으로 오름차순 정렬되어있음.)
- 1번 인덱스 열 : 영화의 id
- 2번 인덱스 열 : 영화의 평점
- 3번 인덱스 열 : 리뷰 입력 시간(단위: 초(유닉스 시간: 1970/01/01를 기준으로 몇초 지났는가))

### 2.데이터의 속성 확인
- 배열 형태
- 차원
- 전체 요소 수 

In [22]:
print(movie.shape)
print(movie.ndim) #몇개의 차원이 있는가 = n 디멘션 함수.
print(movie.size) # 전체 요소의 수

(1000209, 4)
2
4000836


### 3. 전체 영화의 평점들의 평균 구하기

In [7]:
movie

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [8]:
# 전체 영화의 평점에 먼저 접근
# 2차원 배열에서의 데이터 접근 [행의 범위, 열의 범위]

ratings = movie[:,2]

ratings # 평점들

array([5, 3, 3, ..., 5, 4, 4], dtype=int64)

In [11]:
# 전체 영화 평점들의 평균
ratings.mean()

3.581564453029317

In [10]:
np.mean(ratings)

3.581564453029317

In [12]:
round(ratings.mean(),2)

3.58

### 4. 아이디가 1인 사용자가 매긴 영화의 평점들의 평균

In [14]:
# 아이디가 1인 사용자

# 조건 -> 불리언 인덱싱
# id ==1

movie[:,0]==1 #이게 조건식.

array([ True,  True,  True, ..., False, False, False])

In [15]:
# 불리언 인덱싱
# id가 1인 영화 데이터를 id_1이라는 변수에 저장

id_1 =movie[movie[:,0]==1]

id_1

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

In [18]:
# id가 1인 사용자의 평점들

id_1_r=id_1[:,2]

id_1_r

array([5, 3, 3, 4, 5, 3, 5, 5, 4, 4, 5, 4, 4, 4, 5, 4, 3, 4, 5, 4, 3, 3,
       5, 5, 3, 5, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 5, 5, 4, 5, 5, 5, 4, 4,
       4, 5, 5, 4, 5, 4, 4, 4, 4], dtype=int64)

In [19]:
id_1_r.mean()

4.188679245283019

In [21]:
# 중간 변수로 만드는 과정 없이

movie[movie[:,0]==1][:,2].mean() # = id_1[:,2].mean() 

4.188679245283019

### 5. 각 사용자가 매긴 평점들의 평균
- 리스트에 담기

In [23]:
movie

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [24]:
# 데이터의 유효성 검사( id가 정말 6040개 인지)

# 중복값을 제거해주는 (유일한 값들만 구해주는) 함수
# np.unique()

user_id = np.unique(movie[:,0]) # id 값들로 이루어진 배열을 unique함수에 넣음

user_id

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [26]:
len(user_id)
# id는 총 6040개
# 사용자는 6040명

6040

In [27]:
# 오름차순 sort()

asdf = np.array([1,24,142,1,1,34134,14,141])

np.sort(asdf)

array([    1,     1,     1,    14,    24,   141,   142, 34134])

In [31]:
np.sort(user_id) # nd배열은 numpy라이브러리 안에만 있는 자료형이라 np.sort를 써야한다. 그냥 sort함수는 안먹힌다.

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

힌트
- 1번 사용자가 매긴 평점들의 평균 구했다.
- 2번 사용자도 같은 방식
- 6040번 사용자도 같은 방식
- for문
- list에 담기

In [64]:
# 비어있는 리스트를 정의, 각 사용자의 id의 평점의 평균
user_mean_list=[]

for i in user_id:
    user_mean = movie[movie[:,0]==i][:,2].mean()
    #사용자 별로 영화 평점의 평균을 user_mean이라는 변수에 넣어둠
    user_mean_list.append([i,user_mean])

user_mean_list

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

### 6. 각 사용자별 평균 평점이 4점 이상인 사용자만 구하기

In [53]:
user_mean_arr = np.array(user_mean_list)

user_mean_arr

array([[   1.  ,    4.19],
       [   2.  ,    3.71],
       [   3.  ,    3.9 ],
       ...,
       [6038.  ,    3.8 ],
       [6039.  ,    3.88],
       [6040.  ,    3.58]])

In [52]:
# set_printoptions : numpy 배열 출력시 출력 형태 설정 함수
# suppress : 소수점 자리수 고정 출력
# precision : 소수점 자리수 

np.set_printoptions(suppress=True, precision=2)

user_mean_arr

array([[   1.  ,    4.19],
       [   2.  ,    3.71],
       [   3.  ,    3.9 ],
       ...,
       [6038.  ,    3.8 ],
       [6039.  ,    3.88],
       [6040.  ,    3.58]])

In [58]:
# 4점 이상인 데이터
# astype(int)
# 원본에 영향을 안 미침.

user_mean_arr[user_mean_arr[:,1]>=4][:,0].astype(int)

array([   1,    4,    7, ..., 6027, 6032, 6034])

In [57]:
user_mean_arr[user_mean_arr[:,1]>=4][:,0]

array([   1.,    4.,    7., ..., 6027., 6032., 6034.])

### 7. 10번 영화의 평점의 평균.    - 각자 하기

In [60]:
movie[:,1] ==10

array([False, False, False, ..., False, False, False])

In [61]:
movie[movie[:,1] ==10][:,2].mean()

3.5405405405405403

### 8. 각 영화가 받은 평점의 평균

In [62]:
movie_id = np.unique(movie[:,1])

movie_id

array([   1,    2,    3, ..., 3950, 3951, 3952], dtype=int64)

In [65]:
# 비어있는 리스트를 정의, 각 사용자의 id의 평점의 평균
movie_mean_list=[]

for i in movie_id:
    movie_mean = movie[movie[:,1]==i][:,2].mean()
    #사용자 별로 영화 평점의 평균을 user_mean이라는 변수에 넣어둠
    movie_mean_list.append([i,movie_mean])

movie_mean_list

[[1, 4.146846413095811],
 [2, 3.20114122681883],
 [3, 3.01673640167364],
 [4, 2.7294117647058824],
 [5, 3.0067567567567566],
 [6, 3.8787234042553194],
 [7, 3.410480349344978],
 [8, 3.014705882352941],
 [9, 2.656862745098039],
 [10, 3.5405405405405403],
 [11, 3.7938044530493706],
 [12, 2.3625],
 [13, 3.2626262626262625],
 [14, 3.542483660130719],
 [15, 2.458904109589041],
 [16, 3.7932551319648096],
 [17, 4.027544910179641],
 [18, 3.337579617834395],
 [19, 2.480719794344473],
 [20, 2.5375],
 [21, 3.6238938053097347],
 [22, 3.3492063492063493],
 [23, 2.857142857142857],
 [24, 3.1794871794871793],
 [25, 3.6510204081632653],
 [26, 3.53],
 [27, 2.9344262295081966],
 [28, 4.055865921787709],
 [29, 4.062034739454094],
 [30, 3.6486486486486487],
 [31, 3.1134751773049647],
 [32, 3.945731303772336],
 [33, 3.0],
 [34, 3.8914905768132497],
 [35, 3.3142857142857145],
 [36, 3.9579741379310347],
 [37, 3.5],
 [38, 2.8214285714285716],
 [39, 3.6233480176211454],
 [40, 3.933333333333333],
 [41, 3.9586776

In [66]:
movie_mean_arr = np.array(movie_mean_list)

movie_mean_arr

array([[   1.  ,    4.15],
       [   2.  ,    3.2 ],
       [   3.  ,    3.02],
       ...,
       [3950.  ,    3.67],
       [3951.  ,    3.9 ],
       [3952.  ,    3.78]])